maxname: 50
maxemail: 255
minpass: 6
size: 80

linkruby: "http://rubyonrails.org/"
linkrail: "https://www.railstutorial.org/"
linkmh: "http://www.michaelhartl.com/"
linkcdnjs: "//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
linkcontact: "https://www.railstutorial.org/contact"
